[package]
name = "rstvnamer"
version = "0.1.0"
authors = ["dbr"]

[dependencies]
tvdb = "0.4.0"
regex = "0.2.2"

[lib]
name = "rstvnamer"
path = "src/lib.rs"

[[bin]]
name = "tvnamer"
doc = false
path = "src/main.rs"
