[package]
name = "rstvnamer"
version = "0.1.0"
authors = ["dbr"]

[dependencies]
regex = "0.1.8"
hyper = "0.6.11"
xmltree = "0.2.1"

[lib]
name = "rstvnamer"
path = "src/lib.rs"

[[bin]]
name = "tvnamer"
doc = false
path = "src/main.rs"
